detectors:
  Attribute:
    enabled: false
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: true
    exclude: []
  ControlParameter:
    enabled: true
    exclude: []
  DataClump:
    enabled: true
    exclude: []
    max_copies: 3
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: true
    exclude: []
    max_calls: 1
    allow_calls: []
  FeatureEnvy:
    enabled: true
    exclude: []
  InstanceVariableAssumption:
    enabled: true
    exclude: []
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 3
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  ManualDispatch:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: true
    exclude: []
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 2
    ignore_iterators:
    - tap
    - Tempfile.create
  NilCheck:
    enabled: true
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: []
    max_ifs: 2
  SubclassedFromCoreClass:
    enabled: true
    exclude: []
  TooManyConstants:
    enabled: false
    exclude: []
    max_constants: 5
  TooManyInstanceVariables:
    enabled: false
    exclude: []
    max_instance_variables: 4
  TooManyMethods:
    enabled: true
    exclude: []
    max_methods: 20
  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    max_statements: 5
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
    - "/^[a-z]$/"
    - "/[0-9]$/"
    - "/[A-Z]/"
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
    - "/^.$/"
    - "/[0-9]$/"
    accept: []
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
    - "/^.$/"
    - "/[0-9]$/"
    - "/[A-Z]/"
    - "/^_/"
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: []
    reject:
    - "/^.$/"
    - "/[0-9]$/"
    - "/[A-Z]/"
    accept:
    - "/^_$/"
  UnusedParameters:
    enabled: true
    exclude: []
  UnusedPrivateMethod:
    enabled: false
    exclude: []
  UtilityFunction:
    enabled: true
    exclude: []
    public_methods_only: false

# Taken from https://github.com/troessner/reek/blob/master/README.md#working-with-rails
directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
